# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "solvemedia"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eddie Siegel"]
  s.date = "2013-05-29"
  s.description = "Simplifies the use of Solve Media puzzles within rails applications"
  s.email = "plugin@solvemedia.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "generators/solvemedia_config/USAGE",
    "generators/solvemedia_config/solvemedia_config_generator.rb",
    "generators/solvemedia_config/templates/solvemedia_config.yml",
    "init.rb",
    "install.rb",
    "lib/controller_methods.rb",
    "lib/solvemedia.rb",
    "lib/view_methods.rb",
    "solvemedia.gemspec",
    "uninstall.rb"
  ]
  s.homepage = "http://portal.solvemedia.com/portal/help/pub/ruby"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Simplifies the use of Solve Media puzzles within rails applications"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

